version: "3.8"
services:
  mysql:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: your_password # Replace with your desired password
      MYSQL_DATABASE: your_database # Replace with your desired database name
      MYSQL_USER: your_user # Replace with your desired user
      MYSQL_PASSWORD: your_user_password # Replace with your desired user password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  redis:
    image: redis:latest
    command: redis-server --requirepass your_redis_password # Replace with your desired Redis password
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

volumes:
  mysql_data:
  redis_data:
